### ISSUE TITLE
Entities in Home Assistant have double names

### ISSUE THREAD

**Issue by TomStarren** [john30/ebusd#1278]
### Description

I'm currently using the Home Assistant Add-on to get the ebus values in MQTT and HA. This works great, but the entities in HA aren't named correct

### Actual behavior

Entities are names as shown below.
![image](https://github.com/john30/ebusd/assets/74932403/fdeeb29e-0251-4fc6-8778-ccb0c4136701)

### Expected behavior

Entities shouldn't have the ebusd_hmu_ prefix

### ebusd version

23.3

### ebusd arguments

ebusd --foreground --mqtthost=core-mosquitto --mqttport=1883 --mqttuser= --mqttpass= --scanconfig --mqttjson --configpath=/config/ebusd-config/latest/en --latency=20 --pollinterval=5 --mqttint=/etc/ebusd/mqtt-hassio.cfg --mqttvar=topic=%prefix/%circuit/%name --mqtttopic=ebusd --lograwdatafile=/config/ebusd-logs/raw.log --lograwdatasize=100 --device=enh:192.168.40.163:3335 --log=all:error | s6-log 1 n5 s1000000 /config/ebusd-logs

### Operating system

other

### CPU architecture

x64

### Dockerized

latest

### Hardware interface

Adapter Shield v5 via WiFi

### Related integration

MQTT generic, MQTT Home Assistant via mqtt-hassio.cfg

### Logs

.

**Comment by Koky05** [comment]
Name prefix is defined in these file:
`/etc/ebusd/mqtt-hassio.cfg`

**Comment by wrongisthenewright** [comment]
I see this as closed and it may be so but due to a forced HA update due to container corruption to 2024.5.X  I had the same problem, even with an unchanged mqtt-hassio.cfg all ebusd discovered entities had doubled the prefix.
The only way I found to (almost) fix the issue was a python script to bulk rename all the entities. I lost the history, but at least I kept my dashboard running.
