### ISSUE TITLE
ebusd communication through UDP

### ISSUE THREAD

**Issue by rousseldenis** [john30/ebusd#133]
Hi @john30,

I've just tested communication with my installation through the Esera Ethernet/ebus interface and it's rocking fine with TCP mode.

But I'm facing problems when I switch to UDP. I've no signal with the info command.

Do you have implemented it completely or is it not available at the moment (I tested it in python with udp sockets and no more result)?

Thank you for your answer

**Comment by john30** [comment]
UDP is a bit tricky: either you set the device to sending to your ebusd host on a dedicated port (if that's possible at all) or otherwise you'll have to let the device know, where it should send the data. this can probably be achieved by letting ebusd send it an initial escape byte for example, by using the [--initsend](https://github.com/john30/ebusd/wiki/2.-Run#device-options) option
