### ISSUE TITLE
How do I add a value to Home Assistant?

### ISSUE THREAD

**Issue by mpoettgen** [john30/ebusd#1338]
### Description

This could be qualified either as a question or as a request to improve documentation (which I would volunteer to do once I understand the answer).

What I am trying to achieve: I would like to monitor my Vaillant heating system using Home Assistant, especially the **Water Pressure**, since it already happened to me, that the heating system shut down due to low pressure.

I've got the following setup running:
* **Vaillant** heating system
* **ebus Adapter v5**, running latest firmware
* **ebusd**, running on a Raspberry Pi, connected to the ebus Adapter, configured to use MQTT HA integration
* **Home Assistant**, latest, configured with the MQTT integration

I've got five devices in the HA MQTT integration, ebusd, ebusd 700, ebusd bai, abusd broadcast and ebusd eBUS device, all working fine.

I found out from the configuration files/`ebusctl find -f WaterPressure`, that my 700 supports reading WaterPressure.

I can read the WaterPressure using `ebusctl read -c 700 WaterPressure` and it give me an accurate value. I can even get ebusd to poll WaterPressure repeatedly using `ebusctl read -c 700 -p 5 WaterPressure`, but that stops as soon as ebusd is restarted.

I've read somewhere, that polled values are also sent via MQTT, but haven't been able to see any values for WaterPressure in Home Assistant.

What are the best practices to get that value into Home Assistant?

**Comment by john30** [comment]
it needs to be added to the [filter-name entry of the mqtt-hassio.cfg file](https://github.com/john30/ebusd/blob/5d8c9735d227f731cc7e045877d93850b73fc6c6/contrib/etc/ebusd/mqtt-hassio.cfg#L109) in order to be published to HA and polled via [filter-seen](https://github.com/john30/ebusd/blob/5d8c9735d227f731cc7e045877d93850b73fc6c6/contrib/etc/ebusd/mqtt-hassio.cfg#L100), see the [docs how to configure that](https://github.com/john30/ebusd/wiki/MQTT-integration#home-assistant)
