### ISSUE TITLE
VRC700: System off?

### ISSUE THREAD

**Issue by minitrue-nl** [john30/ebusd#182]
Hi John,
Step by step I'm getting further along in the system, connecting my VRC700 to my Loxone Smart Home system...

I can now change requested temperature of the HWC, changing times, etc. I'm just looking for one of the system settings: to turn the complete system off (except for frost protection) for when we are not at home (deep sleep)

Do you know if this could be an option that's not integrated in the csv (yet)? Or could you give some details on the OpMode? Would this be a setting to turn off or on? I don't see any value changing (I've tried reading OpMode and all similar names, but nothing seems to change.) 

Another way around this would be so set the end date of a Holiday. That seems to work, but I would rather use a single command to turn the mode on or off.

Thanks again for all your work so far.

**Comment by john30** [comment]
I would assume that opmode=off would do the trick, but according to the comment, this is only effective on those zones defined in the opmodeeffect message. but anyway, it might be necessary to do that change on the heater rather than the VRC, so I think this would be a hcmode and/or mcmode and/or hwcmode on that side.
