### ISSUE TITLE
write -h

### ISSUE THREAD

**Issue by WWebber** [john30/ebusd#207]
Does not work at all - no matter what I output, always shows the help text. It's not documented, but is it also necessary to add "--enablehex" ?

**Comment by WWebber** [comment]
Answering myself: I added "--enablehex", but it did not help. 
Does "write -h" also output the usage text, when just the passed byte string is faulty?

**Comment by john30** [comment]
> Does "write -h" also output the usage text, when just the passed byte string is faulty?

yes

**Comment by WWebber** [comment]
Then something in the code behaves different as the same string works perfect with the "hex" command.

**Comment by john30** [comment]
you should really read [the wiki](https://github.com/john30/ebusd/wiki/3.1.-TCP-client-commands#write). "write -h ZZPBSBNN[DD]*" is only equal to "hex ZZPBSBNN[DD]*" if there is a message definition associated with the combination of source&destination address, PBSB and optionally parts of the master data.
that's why there is a dedicated hex command...

**Comment by WWebber** [comment]
Hi John, thx, but I still do not understand. Even a command which is processed from the csv (assuming there must exist such a message definition) is not working. Never mind, I use now "hex" instead. What confused me, is there are so many examples which demonstate the "write -h" and almost nobody was using the "hex"..

**Comment by john30** [comment]
you certainly provided non-matching values if that is the case.
where exactly did you find those many examples?

**Comment by TheEPIX** [comment]
I'm just a noob with ebus, but sometimes the fog ist clearing....
So I'm just trying to find out the communication of my WTC25 (weishaupt)
The actual problem is also the hex-writing:

I don't know how to use the "hex" command :-(

A example in Fhem uses
`ebusctl write -h 0850030126 `
to get some answers

I tried this example and also 
```
ebusctl write -h hex0850030126 --enablehex
ebusctl write -h hex 0850030126 --enablehex
ebusctl write -h 0850030126 --enablehex
ebusctl write -hex0850030126 --enablehex
```
nothing bit the "usage-information" of ebusctl...

Any hint (if possibile "simple" for a noob)

**Comment by john30** [comment]
duplicate of #248
