### ISSUE TITLE
add --mqttforce

### ISSUE THREAD

**Issue by john30** [john30/ebusd#219]
to always publish an MQTT message even if the message content did not change at all

**Comment by andig** [comment]
For sake of completeness: this option is also needed if you want to do proper logging:

![img_9406](https://user-images.githubusercontent.com/184815/49003388-1b2fb300-f162-11e8-8312-3eb5d57ecb92.jpg)

The yelllow solid line should in reality follow the dashed line. It doesn't since- without this option- ebusd silently ignores the repeated values. In the end, the logged temperature curve is therefore wrong.

@john30 might even make sense to swap the behaviour, i.e. make this option the default?

**Comment by Dinth** [comment]
Great news! I hope this will also be a workaround for my problem #222

**Comment by andig** [comment]
Would be great to get this into 3.3, I'm really looking forward to monitor my heating in more detail...

**Comment by john30** [comment]
fixed with a84c3cb296730d86e89e8153e5cde5df8b23fe01
