### ISSUE TITLE
Where to find and edit the configuration files when using /ebusd.eu/config/

### ISSUE THREAD

**Issue by twischi** [john30/ebusd#317]
Dear All,
with ebusd I am using the automatic configuration with getting the newest files from "ebusd.eu" what is working fine.
`--configpath=http://ebusd.eu/config/`

I want to manipulate the configuration to write values with the SetMode command (I am using no "regulator" on ebus).
But I have the simple problem: I don't find the files

`vaillant/bai.0010006101.inc`
`vaillant/08.bai.csv` 

to modify the config.

`sudo find / -name 08.bai.csv`  leads to no result

Guess they are only existing in memory, when using this auto-config?
If not where to find? 

Regards
Thomas

**Comment by Maddin2020** [comment]
I think you must only use Google then you can found the files on Guthaben and you can copy this Files to your system

**Comment by Maddin2020** [comment]
https://github.com/john30/ebusd-configuration/blob/master/ebusd-2.1.x/de/vaillant/08.bai.csv

**Comment by Maddin2020** [comment]
.com/john30/ebusd-configuration/blob/master/ebusd-2.1.x/de/vaillant/bai.0010006101.inc

**Comment by Maddin2020** [comment]
https://github.com/john30/ebusd-configuration/blob/master/ebusd-2.1.x/de/vaillant/bai.0010006101.inc

**Comment by john30** [comment]
it is [described here](https://github.com/john30/ebusd-configuration/blob/master/README.md)

**Comment by domi-a** [comment]
@twischi did you manage to find, manipulate and use config files to write with SetMode?
it is exactly what i want to. but i dont get it to work.

i copied the files from 
https://github.com/john30/ebusd-configuration/tree/master/ebusd-2.1.x/en to /etc/config
and started the deamon with
 `-f --scanconfig --configpath=/etc/config/ --accesslevel=* -d tcp:192.168.3.57:9999 --latency=80000 --mqttport=1883 --mqtthost=192.168.3.27`
i'm not sure if `scanconfig `is supposed to be used with `configpath`
and i have no clue how to manipulate the files or wich files so that the command:
`ebusctl write -c bai SetMode "auto;0.0;-;-;1;0;1;0;0;0"`
will work. it still respondes with 
`ERR: element not found`

**Comment by twischi** [comment]
@domi-a: sorry, no for me it never worked and than i lost track.
Guess in my system the problem COULD be that I took the external regulator "calorMatic 470f" out of my system. Maybe only this device would have been able to take write commands. But I am not sure.

My Vaillant System: VSC 126/3-5 140-HL
not used external regulator @ebus  calorMatic 470f

**Comment by john30** [comment]
if you cloned the files to /etc/config, then simply edit /etc/config/vaillant/hcmode.inc in line 10 and replace the "uw" at the beginning of the line with a "w". Then SetMode will be writable after you have restarted ebusd.
