### ISSUE TITLE
udp connection only

### ISSUE THREAD

**Issue by RoSulek1** [john30/ebusd#423]
ebusd adapter3 with wemos wifi connection.
Only on UDP connection on port 9999 i have ebusd connected. On TCP or Enhanced connection there is no connecion. Is this normal?

![image](https://user-images.githubusercontent.com/35807309/116138883-aae03f80-a6d5-11eb-8f26-adea2d5c870a.png)

**Comment by netweaver1970** [comment]
What is your configuration screen settings?
![image](https://user-images.githubusercontent.com/18028618/116535149-b2753380-a8e3-11eb-936f-5ee9dee5e9f5.png)

What is your device string when you start ebusd? 
Below are mine: 2 variants: once direct, once via docker. The docker port config looks a bit funny but hat's because there's a current issue with the latest docker on systems with IPV6 disabled. The mqtttopic parameter is not needed, as it's the same as the default.

`docker run --rm -it -p “0.0.0.0:8888:8888/tcp” john30/ebusd:devel -f --scanconfig -d enh:192.168.0.128:9999 --mqttport=1883 --mqtthost=192.168.0.11 --mqttuser=****** -d enh:192.168.0.95:9999 --mqttpass=***** --mqttjson --mqtttopic=ebusd/%circuit/%name --latency=20000 –loglevel=debug`

`ebusd -f --scanconfig --mqttport=1883 --mqtthost=192.168.0.11 --mqttuser=****** -d enh:192.168.0.95:9999 --mqttpass=****** --mqttjson --mqtttopic=ebusd/%circuit/%name --latency=20000 -–loglevel=debug`

**Comment by RoSulek1** [comment]
ebusd device string: udp:192.168.0.141:9999,
There is no any connection to ebusd from wemos on tcp or enhanced
connection :(
I dont know im' doing something wrong :/

docker run --rm -it -p 8888 john30/ebusd:devel -f --scanconfig -d udp:
192.168.0.141:9999 --loglevel=debug --ble, ble ble ;)
docker connect with mqtt, but there is no output of ebusctl info

![image](https://user-images.githubusercontent.com/35807309/116569780-fda23d00-a909-11eb-8ae9-34764055aca4.png)

**Comment by john30** [comment]
enhanced proto is tcp only and you need to use "enh:<ip>:9999" on ebusd
