### ISSUE TITLE
Enable cooling on VRC700

### ISSUE THREAD

**Issue by minitrue-nl** [john30/ebusd#438]
Quick question:

I'm trying to get cooling to work on my VRC700 via ebusd, but I cannot find the right commands. So I'm trying to put my heat pump system in cooling mode, either trough the main settings, or as manually cooling (setting for a number of days.)
Can somebody point me in the right direction?

**Comment by mwildbolz** [comment]
Same problem here - haven't found the right codes at the moment.
Probably there is another possible value for the operatingMode fields - other than the ones provided?

**Comment by InToSSH** [comment]
I would like to see this option too. For some reason my VRC700 doesn't switch my heatpump to cooling automatically (although it should based on what Vaillant technician told me), I have to enable it manually, but this change is not reflected on any of those commands.

**Comment by minitrue-nl** [comment]
No news here, but I will ask my Vaillant technician again about the option of switching to cooling automatically. Although I don't expect to use it in the short term with the Belgian summer we had. 😢 I'll post here if I know more.

**Comment by InToSSH** [comment]
Thanks for the update. Yea it was the same with summer here in Czech republic, but we had like two weeks of hot weather and it would be nice to have this option to enable the cooling remotely before we returned from the vacation. I didn't make any progress so far, I see some undecoded values coming from the heatpump itself but I can't seem to find any sense in them.

**Comment by nafgarda** [comment]
Here in Spain this is an issue...
VRC 700 it is not very predictable when you set up cooling automatically according to the scheduling. It is said that it uses a kind of averaged external temperature as an input parameter an require time to initialize after power down with apropiate external temperature.
Regarding ebusd, haven't find either a parameter to start or stop the cooling. It is essential to have it in summer.

Regards

**Comment by InToSSH** [comment]
Right, I couldn't get it to work in auto mode, it didn't star the whole summer and we had quite a lot of hot days. I always had to turn it on manually. Even called Vaillant about it, and they basically said the same as you and couldn't help further.

**Comment by mwildbolz** [comment]
Regarding how it works - as I have observed it:
As you said, there is an averaged outside temperature (also pollable via VRC700!).

For starting the cooling mode, this averaged outside temperature AND the actual outside temp have to be higher than the cooling starting temperature parameter in the configuration (in my case 23°C).
Cooling stops, if the actual outside temp falls below the cooling switch off temperature parameter in the configuration (in my case 17°C).
So, there is a quite big hysteresis and the averaged temperature takes quite long till it reaches the switch-on-point.

What I have observed in addition is, that the averaging is reset if you power-cycle the heatpump. Meaning, directly after the power cycle the average temp. equals the actual outside temp.

My this helps a little bit.
But, the problem is also for me, that I haven't found a way to control the cooling mode via ebusd...

**Comment by javierin** [comment]
I've been using ebusd for almost a year with a Saunier Duval rebranded arotherm split 8 + VRC720. I am about to set everything up again, because I have a defective microsd in my EBUS RPi and also made an absolute mess setting things up a year ago.

@nafgarda Do you own a Vaillant or a Saunier Duval unit?

**Comment by nafgarda** [comment]
I've got Vaillant.
Regarding this question it would be nice to know how all of you are controlling the whole system. Just to share ideas.

My zones are not controlled by Vaillant, so that is the plan. I have 9 analog thermostat and 11 zones controlled with 11 solenoids. My plan is to replace the analog thermostats with Shelly wifi relays equipped with a thermocouple. At first I would use the Shelly cloud interface to set up the desired temperatures and it scheduling. My solenoids have a dry contact circuit that tells if they are open or close. That circuit from all solenoids is already connected to the heat pump and when all the solenoids are close, the heating stops automatically. 

I'm planning to use as well ebusd with Node Red installed in the same RPI:

1. I will set up an interface to activate or disactivate the whole system using Exec node and commands like "ebus ebusctl  write -c 700 HwcOpmode day"
2. I will probably set up interfaces to change the schedules in the VRC700.
3. I will set up a rule in node red that will switch off the heat pump when the demanded power measured at home with a Shelly EM goes over the power limit. Here in Spain we pay a fixed tariff to the electric utility according to the maximum power you can use. The electricity meters power down the system when you pass the limit (with some thresholds). So it is cheaper to have a lower limit.
4. As I will also install a 4 kWp photovoltaic system on the roof in near future, I will set up rules in Node Red to use the solar surplus in two different ways: rising the the temperature of the whole house opening the solenoids with the shelly relays and/or heating water in the cylinder with ebusd.

Total aprox budget: 
130 euros in Shelly relays and Energy Meter
30 euros from and old RPI2
20 euros from EBUS USB interface

That's all I think.
Hope it is useful for others
Comments are welcome.

**Comment by javierin** [comment]
I am only interested in pushing hot water control commands through ebus, as I don't have any other thermostat different from the remote control unit. I turn the fancoils on and off using plugs (the fancoil units remember their last state).

**Comment by john30** [comment]
please discuss in the right area (e.g. https://github.com/john30/ebusd-configuration/issues/), not here as this repo is for the source code of ebusd and not for configurations
