### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by moskovskiy82** [john30/ebusd#449]
Feeling really frustrated getting this to run. Installed bia the repos on ubuntu server 20.04
Took me around 30 minutes to understand which command to run first 
ebusd -d 172.16.xx.xx:9999 --scanconfig

Then following the instructions checkconfig?
Killed the daemon 
and then 
ebusd -d 172.16.xx.xx:9999 --checkconfig
just to get the following
[main error] invalid configpath without scanconfig

Where to dig next docs just dont say. The configuration path /ets/ebusd is empty

**Comment by Commifreak** [comment]
I was wondering as well were to start.

/etc/ebusd is empty, yes, because per default, the configs are loaded from `http://ebusd.eu/config/`.

You could do a `ebusctl i` to view detected system so far. To interact with ebusd one have to send commands to HTTP-Port 8888 or read something via ebusctl.

You could also set `--httpport=PORT` to view a JSON output.

Iam still testing, since I got another problem preventing me from going further.

**Comment by john30** [comment]
then please make a proposal by making a pull request.
A lot of info is in the [wiki](https://github.com/john30/ebusd/wiki).

**Comment by john30** [comment]
closed due to inactivity
